# Generated by Django 5.0.4 on 2025-03-31 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Váha v kg')),
                ('height', models.FloatField(help_text='Výška v cm')),
                ('age', models.PositiveIntegerField(help_text='Věk v letech')),
                ('gender', models.CharField(choices=[('M', 'Muž'), ('F', 'Žena')], max_length=1)),
                ('basal_metabolic_rate', models.FloatField(help_text='Bazální metabolismus v kcal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
