# Generated by Django 5.1.7 on 2025-03-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementunit',
            name='code',
            field=models.CharField(help_text='Short code of the unit (eg. m)', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='full_name',
            field=models.CharField(help_text='Full name of the unit (eg. Meters)', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='si',
            field=models.BooleanField(help_text='Is this unit standard SI measurement unit? Example of SI unit is meter, while steps is not. SI measurement units will get automatic conversion based on SI spec (example: 1000 m -> 1 km)'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='calories_per_unit',
            field=models.FloatField(help_text='How many calories you burn per measurement unit in this sport. For example climbing is 300 calories per hour of climbing'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='code',
            field=models.CharField(help_text='Short code of the sport (eg. RUN)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(help_text='Name of the sport (eg. Running)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='unit',
            field=models.ForeignKey(help_text='Unit that this sport is measured in. For running, this would be meters', on_delete=django.db.models.deletion.CASCADE, to='core.measurementunit'),
        ),
    ]
